### ISSUE TITLE
Please see it,thanks

### ISSUE THREAD

**Issue by DrayChou** [ruhoh/ruhoh.rb#11]
```
E:\Dray\Git\ruhoh\draychou.ruhoh.com>gem install ruhoh
Fetching: mustache-0.99.4.gem (100%)
Fetching: ruhoh-0.1.0.gem (100%)
Successfully installed mustache-0.99.4
Successfully installed ruhoh-0.1.0
2 gems installed
Installing ri documentation for mustache-0.99.4...
Installing ri documentation for ruhoh-0.1.0...
Installing RDoc documentation for mustache-0.99.4...
Installing RDoc documentation for ruhoh-0.1.0...

E:\Dray\Git\ruhoh\draychou.ruhoh.com>rackup -p 9292
0 posts to process.
0 drafts to process.
[32m6/6 pages processed.[0m
E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/lib/ruhoh/utils
.rb:38:in `rescue in parse_file': uninitialized constant Psych::SyntaxError (Nam
eError)
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/li
b/ruhoh/utils.rb:22:in `parse_file'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/li
b/ruhoh/parsers/layouts.rb:11:in `block in generate'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/li
b/ruhoh/parsers/layouts.rb:9:in `each'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/li
b/ruhoh/parsers/layouts.rb:9:in `generate'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/li
b/ruhoh/db.rb:26:in `update'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/li
b/ruhoh/db.rb:39:in `block in update!'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/li
b/ruhoh/db.rb:38:in `each'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/li
b/ruhoh/db.rb:38:in `update!'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.0/li
b/ruhoh/previewer.rb:18:in `initialize'
        from E:/Dray/Git/ruhoh/draychou.ruhoh.com/config.ru:10:in `new'
        from E:/Dray/Git/ruhoh/draychou.ruhoh.com/config.ru:10:in `block in <mai
n>'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/builder.rb:51:in `instance_eval'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/builder.rb:51:in `initialize'
        from E:/Dray/Git/ruhoh/draychou.ruhoh.com/config.ru:1:in `new'
        from E:/Dray/Git/ruhoh/draychou.ruhoh.com/config.ru:1:in `<main>'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/builder.rb:40:in `eval'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/builder.rb:40:in `parse_file'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/server.rb:200:in `app'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/server.rb:301:in `wrapped_app'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/server.rb:252:in `start'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/server.rb:137:in `start'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/bin
/rackup:4:in `<top (required)>'
        from E:/RailsInstaller/Ruby1.9.2/bin/rackup:19:in `load'
        from E:/RailsInstaller/Ruby1.9.2/bin/rackup:19:in `<main>'
```

**Comment by DrayChou** [comment]
E:\Dray\Git\ruhoh\draychou.ruhoh.com>ruhoh help

```
Ruhoh is a nifty, modular static blog generator.
It is the Universal Static Blog API.
Visit http://www.ruhoh.com for complete usage and documentation.

Use `ruhoh help` for full command list.
    -e, --ext [EXT]                  Specify filename extension. Defaults to '.m
d'
    -v, --[no-]verbose               Run verbosely. For pages, shows extra title
, url meta-data.
        --version                    Display current gem and ruhoh specification
 versions.

Commands:

[32m  new <directory_path>[0m
    Create a new blog directory based on the Ruhoh specification.
[32m  compile[0m
    Compile to static website.
[32m  draft[0m
    Create a new draft.
[32m  publish[0m
    Publish the last active draft file.
[32m  unpublish[0m
    UnPublish the last active post file.
[32m  page <path>[0m
    Create a new page at the given path.
[32m  drafts[0m
    List all drafts.
[32m  posts[0m
    List all posts.
[32m  pages[0m
    List all pages.
[32m  payload[0m
    List the full payload hash as given to the templater. Note page is blank for
 example purposes.
[32m  layout <name>[0m
    Create a new layout for the currently active theme.
[32m  theme <name>[0m
    Create a new theme scaffold.
[32m  help[0m
    Show this menu.
```

**Comment by plusjade** [comment]
@DrayChou it seems that Psych::SyntaxError is not loading which is in the YAML library. There was a similar issue with JSON not being properly required and it was also on a windows machine. Do you know how to run gems via bundler?

This way I will update the source with the fix and then you can run the gem from the git repository and see that the fix works. This is the only way we can be sure the fix solves the problem.

If you don't know how to use bundler I can provide some instructions here for you, please let me know though so we can address this issue. Thanks!

**Comment by DrayChou** [comment]
like this?

```
E:\Dray\Git\ruhoh\draychou.ruhoh.com>bundle exec ruhoh
Could not locate Gemfile

E:\Dray\Git\ruhoh\draychou.ruhoh.com>bundle exec ruhoh help
Could not locate Gemfile

E:\Dray\Git\ruhoh\draychou.ruhoh.com>bundle exec ruhoh -p 9292
Could not locate Gemfile
```

**Comment by plusjade** [comment]
@DrayChou I have realized it is because YAML is trying to use syck rather than psych parser.
Can you uninstall ruhoh then re-install it?

``` bash
$ gem uninstall ruhoh
$ gem install ruhoh --version 0.1.2
```

Let me know if this works. If not you may have to install the `psych` gem manually but it should be part of ruby 1.9.x standard library.

**Comment by DrayChou** [comment]
Sorry, there is another mistake, file path is wrong, and what's [32m ?

![error message](http://s2.i1.picplzthumbs.com/upload/img/14/e7/21/14e72188819b814b81040db090bdc4d102e29f0e_wmeg.jpg)

```
E:\Dray\Git\ruhoh\draychou.ruhoh.com>rackup -p 9292
0 posts to process.
0 drafts to process.
[32m6/6 pages processed.[0m
E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.2/lib/ruhoh/utils
.rb:25:in `parse_file': File not found: E:/Dray/Git/ruhoh/draychou.ruhoh.com/E:/
Dray/Git/ruhoh/draychou.ruhoh.com/_templates/themes/twitter/layouts/default.html
 (RuntimeError)
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.2/li
b/ruhoh/parsers/layouts.rb:11:in `block in generate'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.2/li
b/ruhoh/parsers/layouts.rb:9:in `each'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.2/li
b/ruhoh/parsers/layouts.rb:9:in `generate'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.2/li
b/ruhoh/db.rb:26:in `update'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.2/li
b/ruhoh/db.rb:39:in `block in update!'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.2/li
b/ruhoh/db.rb:38:in `each'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.2/li
b/ruhoh/db.rb:38:in `update!'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/ruhoh-0.1.2/li
b/ruhoh/previewer.rb:18:in `initialize'
        from E:/Dray/Git/ruhoh/draychou.ruhoh.com/config.ru:10:in `new'
        from E:/Dray/Git/ruhoh/draychou.ruhoh.com/config.ru:10:in `block in <mai
n>'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/builder.rb:51:in `instance_eval'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/builder.rb:51:in `initialize'
        from E:/Dray/Git/ruhoh/draychou.ruhoh.com/config.ru:1:in `new'
        from E:/Dray/Git/ruhoh/draychou.ruhoh.com/config.ru:1:in `<main>'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/builder.rb:40:in `eval'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/builder.rb:40:in `parse_file'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/server.rb:200:in `app'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/server.rb:301:in `wrapped_app'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/server.rb:252:in `start'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/lib
/rack/server.rb:137:in `start'
        from E:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/rack-1.4.1/bin
/rackup:4:in `<top (required)>'
        from E:/RailsInstaller/Ruby1.9.2/bin/rackup:19:in `load'
        from E:/RailsInstaller/Ruby1.9.2/bin/rackup:19:in `<main>'

E:\Dray\Git\ruhoh\draychou.ruhoh.com>ruhoh help

Ruhoh is a nifty, modular static blog generator.
It is the Universal Static Blog API.
Visit http://www.ruhoh.com for complete usage and documentation.

Use `ruhoh help` for full command list.
    -e, --ext [EXT]                  Specify filename extension. Defaults to '.m
d'
    -v, --[no-]verbose               Run verbosely. For pages, shows extra title
, url meta-data.
        --version                    Display current gem and ruhoh specification
 versions.

Commands:

[32m  new <directory_path>[0m
    Create a new blog directory based on the Ruhoh specification.
[32m  compile[0m
    Compile to static website.
[32m  draft[0m
    Create a new draft.
[32m  publish[0m
    Publish the last active draft file.
[32m  unpublish[0m
    UnPublish the last active post file.
[32m  page <path>[0m
    Create a new page at the given path.
[32m  drafts[0m
    List all drafts.
[32m  posts[0m
    List all posts.
[32m  pages[0m
    List all pages.
[32m  payload[0m
    List the full payload hash as given to the templater. Note page is blank for
 example purposes.
[32m  layout <name>[0m
    Create a new layout for the currently active theme.
[32m  theme <name>[0m
    Create a new theme scaffold.
[32m  help[0m
    Show this menu.
```

**Comment by plusjade** [comment]
ive seen this before.... I will fix this.  seems the windows path is not
being handled correctly

**Comment by plusjade** [comment]
@DrayChou please try just released version 0.1.3, I've added a fix but cannot be sure it works because I don't have access to a Windows machine with ruby environment. Thank you for your continued debugging support and let me know if this works.

Also  [32m is an ANSI escape code for color-coding terminal output. A quick summary here: http://stackoverflow.com/questions/2616906/how-do-i-output-coloured-text-to-a-linux-terminal

I don't think it works on Windows terminals, and I have an option in place to disable it but it is not hooked up yet =/ I will let you know when I implement the option.

**Comment by DrayChou** [comment]
The good news, now can run normally. All pages showing no problem, but I don't have any other part of the test, wait a moment to have time I'll go with him, thank you.

E:\Dray\Git\ruhoh\draychou.ruhoh.com>rackup -p 9292
0 posts to process.
0 drafts to process.
[32m6/6 pages processed. [0m
=> Start watching: E:/Dray/Git/ruhoh/draychou.ruhoh.com
[2012-04-19 17:37:22] INFO  WEBrick 1.3.1
[2012-04-19 17:37:22] INFO  ruby 1.9.2 (2011-07-09) [i386-mingw32]
[2012-04-19 17:37:22] INFO  WEBrick::HTTPServer#start: pid=7788 port=9292

As for the operation environment, this is not way to things, the computers of the company is all Windows system, and now I have no other computer. Later, I would buy a Linux or MAC system of computer.

thanks

**Comment by plusjade** [comment]
Glad it worked. For what it is worth, I hope to fully support ruhoh on Windows machines, it's just  I don't have access to a Windows machine with a ruby environment that works ;)

**Comment by DrayChou** [comment]
Thank you, if I encounter problems, I will timely issue,
