### ISSUE TITLE
 uninitialized constant Ruhoh::Resources::Base

### ISSUE THREAD

**Issue by motord** [ruhoh/ruhoh.rb#120]
```
peter@diablo:~/Projects/banter$ bundle exec rackup -p 9292
/home/peter/.rvm/gems/ruby-1.9.3-p194/bundler/gems/ruhoh.rb-a1330ceeac06/lib/ruhoh/resources/media/collection.rb:2:in `<module:Media>': uninitialized       constant Ruhoh::Resources::Base (NameError)
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bundler/gems/ruhoh.rb-a1330ceeac06/lib/ruhoh/resources/media/collection.rb:1:in `<top (required)>'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bundler/gems/ruhoh.rb-a1330ceeac06/lib/ruhoh/resources_interface.rb:3:in `require'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bundler/gems/ruhoh.rb-a1330ceeac06/lib/ruhoh/resources_interface.rb:3:in `block in <top (required)>'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bundler/gems/ruhoh.rb-a1330ceeac06/lib/ruhoh/resources_interface.rb:2:in `each'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bundler/gems/ruhoh.rb-a1330ceeac06/lib/ruhoh/resources_interface.rb:2:in `<top (required)>'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bundler/gems/ruhoh.rb-a1330ceeac06/lib/ruhoh.rb:27:in `require'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bundler/gems/ruhoh.rb-a1330ceeac06/lib/ruhoh.rb:27:in `<top (required)>'
from /home/peter/Projects/banter/config.ru:2:in `require'
from /home/peter/Projects/banter/config.ru:2:in `block in <main>'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.2/lib/rack/builder.rb:51:in `instance_eval'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.2/lib/rack/builder.rb:51:in `initialize'
from /home/peter/Projects/banter/config.ru:in `new'
from /home/peter/Projects/banter/config.ru:in `<main>'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.2/lib/rack/builder.rb:40:in `eval'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.2/lib/rack/builder.rb:40:in `parse_file'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.2/lib/rack/server.rb:200:in `app'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.2/lib/rack/server.rb:304:in `wrapped_app'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.2/lib/rack/server.rb:254:in `start'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.2/lib/rack/server.rb:137:in `start'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.2/bin/rackup:4:in `<top (required)>'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bin/rackup:19:in `load'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bin/rackup:19:in `<main>'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
from /home/peter/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by douo** [comment]
same issue.
I found it cause by the require order of the resources file.

change

``` ruby
Dir[File.join(File.dirname(__FILE__), 'resources', '**', '*.rb')].each
```

to

``` ruby
Dir[File.join(File.dirname(__FILE__), 'resources', '**', '*.rb')].sort.each
```

in this [line](https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/resources_interface.rb#L2) will fix it.

**Comment by plusjade** [comment]
@douo thanks for the help. Looks really simple when you point it out!

@motord please verify it works by updating the gem:

``` bash
$ rm Gemfile.lock
$ bundle install
```

**Comment by motord** [comment]
Fix verified.
Thanks @douo @plusjade
