### ISSUE TITLE
Upgrading from vX.Y -> v2.1 -> v2.2

### ISSUE THREAD

**Issue by coolaj86** [ruhoh/ruhoh.rb#195]
Here's the process that I've had to use because there's currently no way of knowing which component failed.

First I migrate posts into the empty template. Some of them won't parse anymore. Who knows why.

``` bash
OLDBLOG=blog.coolaj86.com
NEWBLOG=new-blog

pushd ~/Blogs
git clone 'git://github.com/ruhoh/blog.git' "${NEWBLOG}"
pushd ${NEWBLOG}
bundle install
popd

mkdir -p posts-bad-syntax
mkdir -p posts-good

ls "${OLDBLOG}/posts/" | while read POST
do
  mv "${OLDBLOG}/posts/${POST}" "${NEWBLOG}/posts/" \
    && bash -c "pushd ${NEWBLOG}; bundle exec ruhoh compile; popd" \
    && mv "${NEWBLOG}/posts/${POST}" "posts-good/" \
    || mv "${NEWBLOG}/posts/${POST}" "posts-bad-syntax/"
done

mv ${OLDBLOG} ${OLDBLOG}.old
mv ${NEWBLOG} ${OLDBLOG}
```

And then I can more easily play with the broken posts and figure out why posts that had valid syntax before no longer have valid syntax.

``` bash
git clone 'git://github.com/ruhoh/blog.git' new-blog-2
pushd new-blog-2
mv ../posts-bad-syntax/something.html new-blog-2/posts/
bundle exec ruhoh compile
```

Likewise I'm just moving `about.html`, `index.html`, etc over one at a time.

I'll have to report back on migrating my modified theme.

Also I'm using ruby 1.9.3. I don't think 2.0.0 works with ruhoh.

**Comment by coolaj86** [comment]
But then when I move all of the posts from `posts-good` to `${NEWBLOG}/posts` and try to compile it as a whole, it still fails.

```
/Users/coolaj86/.rvm/gems/ruby-1.9.3-p429/gems/ruhoh-2.1/lib/ruhoh/base/model_view.rb:47:in `parse': can't convert Date into String (TypeError)
    from /Users/coolaj86/.rvm/gems/ruby-1.9.3-p429/gems/ruhoh-2.1/lib/ruhoh/base/model_view.rb:47:in `<=>'
    from /Users/coolaj86/.rvm/gems/ruby-1.9.3-p429/gems/ruhoh-2.1/lib/ruhoh/resources/pages/collection_view.rb:12:in `sort'
    from /Users/coolaj86/.rvm/gems/ruby-1.9.3-p429/gems/ruhoh-2.1/lib/ruhoh/resources/pages/collection_view.rb:12:in `all'
    from /Users/coolaj86/.rvm/gems/ruby-1.9.3-p429/gems/ruhoh-2.1/lib/ruhoh/resources/pages/collection_view.rb:40:in `collated'
...
    from /Users/coolaj86/.rvm/gems/ruby-1.9.3-p429/bin/ruhoh:19:in `<main>'
    from /Users/coolaj86/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/coolaj86/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by coolaj86** [comment]
I got lucky on binary search bingo and found out that two particular posts were causing the entire thing to fail:

https://gist.github.com/coolaj86/e30e5ae43013ad1cd1b0

One fails because the mustache escape `{{=<|| ||>=}}` isn't being respected.

The other... no idea yet.

**Comment by Stebalien** [comment]
Why aren't you using 2.2? It includes a fix for the date parsing bug (#153) and the compile time was vastly improved in (2.1.1) 536a38cde9e7da833b9ba6efd895bae20216fdf8.

If you still have compile time problems, try applying #179.

The escape sequence should be: {{#raw_code}} code {{/raw_code}} (although it isn't documented, #187)

Also, Ruhoh 2.2 works perfectly with ruby 2.0.

**Comment by coolaj86** [comment]
This is why: http://ruhoh.com/ ... I was just following the instructions. Now I'll look for the 2.2 instructions.

**Comment by coolaj86** [comment]
P.S. Where are the 2.2 instructions?

```
vim Gemfile
# change 2.1 -> 2.2
bundle install
```

**Comment by Stebalien** [comment]
Well, that explains that.

As far as I know, there weren't any major API changes between versions 2.1 and 2.2. The author appears to be busy with real life lately and therefore hasn't been able to work on ruhoh related tasks. And yes, changing the version in the Gemfile should be sufficient.

**Comment by coolaj86** [comment]
Awesome! do you happen to know how I tell it to ignore a folder?

example:

```
twitter:
  use: "theme"

drafts:
  use: "ignore"

junk:
  use: "ignore"
```

**Comment by coolaj86** [comment]
I just realized that all of my `<link rel=canonical href={{urls.production_url}}{{url}}>` are broken and hence likes, g+, tweet shares all have the wrong url.

What's the new `{{ url }}` that I can use in default.html and uses the url of a specific post? I tried `{{ page.url }}` to no avail.

**Comment by Stebalien** [comment]
> Awesome! do you happen to know how I tell it to ignore a folder?

As far as I know, ruhoh doesn't have this functionality out of the box. However, the following plugin should do the trick:

``` ruby
module Ruhoh::Resources::Ignore
  class Collection
    include Ruhoh::Base::Collectable
  end
end
```

**Comment by Stebalien** [comment]
`{{ page.url }}` works for me but `{{ urls.production_url}}` does appear to be broken (pull request #196).

**Comment by snowe2010** [comment]
If you need to ignore a folder, you can edit the `config.yml` file. http://ruhoh.com/docs/2/ignore/
