### ISSUE TITLE
Gem dependency update

### ISSUE THREAD

**Issue by waynedpj** [ruhoh/ruhoh.rb#238]
at the time of this writing it seems that the Quick Start docs need to be updated to include another Gem dependency: on the page http://ruhoh.com/docs/2/#toc_1 under "Launch" i had to add

```
gem 'json'
```

to my Gemfile for ruhoh to run properly.  i am running the following versions:

```
ruby 1.9.3p448 (2013-06-27 revision 41675)
Using ruhoh (2.5) 
Using bundler (1.3.5) 
```

hope this helps and thanks for ruhoh, looking forward to trying it out.

peace

**Comment by waynedpj** [comment]
update: running ruho from git master i still see the dependency on json:

```
$ bundle exec ruhoh server 9262
/home/waynedpj/.gem/ruby/1.9.1/bundler/gems/ruhoh.rb-182e9f452f04/lib/ruhoh.rb:3:in `require': cannot load such file -- json (LoadError)
    from /home/waynedpj/.gem/ruby/1.9.1/bundler/gems/ruhoh.rb-182e9f452f04/lib/ruhoh.rb:3:in `<top (required)>'
    from /home/waynedpj/.gem/ruby/1.9.1/bundler/gems/ruhoh.rb-182e9f452f04/bin/ruhoh:5:in `require'
    from /home/waynedpj/.gem/ruby/1.9.1/bundler/gems/ruhoh.rb-182e9f452f04/bin/ruhoh:5:in `<top (required)>'
    from /home/waynedpj/.gem/ruby/1.9.1/bin/ruhoh:23:in `load'
    from /home/waynedpj/.gem/ruby/1.9.1/bin/ruhoh:23:in `<main>'
```

my current working setup is

```
Resolving dependencies...
Using directory_watcher (1.4.1) 
Using json (1.8.1) 
Using mini_portile (0.5.2) 
Using mustache (0.99.5) 
Using nokogiri (1.6.0) 
Using rack (1.5.2) 
Using redcarpet (2.3.0) 
Using ruhoh (2.5) from git://github.com/ruhoh/ruhoh.rb.git (at master)
```

```
$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

```
$ bundle exec ruhoh --version
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
ruhoh 2.5
RuhohSpec 2.1
```

just an FYI to update the Launch section of the Quick Start as mentioned above.
