### ISSUE TITLE
Can't seem to get assets pipeline to work

### ISSUE THREAD

**Issue by richtera** [ruhoh/ruhoh.rb#240]
I get this error:

``` ruby
/Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/system/plugins/sprockets/stylesheets/compiler.rb:11:in `join': no implicit conversion of nil into String (TypeError)
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/system/plugins/sprockets/stylesheets/compiler.rb:11:in `block in run'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/system/plugins/sprockets/stylesheets/compiler.rb:10:in `each'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/system/plugins/sprockets/stylesheets/compiler.rb:10:in `run'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/lib/ruhoh.rb:198:in `block in compile'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/lib/ruhoh.rb:195:in `each'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/lib/ruhoh.rb:195:in `compile'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/lib/ruhoh/programs/compile.rb:19:in `compile'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/lib/ruhoh/client.rb:101:in `block in compile'
    from /Users/andy/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/lib/ruhoh/client.rb:100:in `compile'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/lib/ruhoh/client.rb:34:in `initialize'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/bin/ruhoh:34:in `new'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/gems/ruhoh-2.1/bin/ruhoh:34:in `<top (required)>'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/bin/ruhoh:23:in `load'
    from /Users/andy/.rvm/gems/ruby-2.0.0-p247/bin/ruhoh:23:in `<main>'
```

It looks like in this part of the code, the h variable is just a path and not an object containing a path member:

``` ruby
      Ruhoh::Friend.say { cyan "Stylesheets: (using sprockets)" }
      env = Sprockets::Environment.new
      env.logger = Logger.new(STDOUT)
      @collection.paths.reverse.each do |h|
        env.append_path(File.join(h["path"], @collection.resource_name))
      end
```

Not sure where this is going wrong. It's almost like a collection used to contain "path" and "id" and not is just a list of files. Not sure what to look at next.

**Comment by richtera** [comment]
Works with the git hosted version. Looks like the rubygems hosted version has this problem.
