### ISSUE TITLE
collection_view.rb:15:in `sort': comparison of Ruhoh::Resources::Pages::ModelView with Ruhoh::Resources::Pages::ModelView failed (ArgumentError) after adding _root/CNAME

### ISSUE THREAD

**Issue by pzol** [ruhoh/ruhoh.rb#266]
CNAME contains

```
rustbyexample.nobacon.it
```

``` shell
➜  rust_by_example git:(master) ✗ bundle exec ruhoh compile
Using theme: "theme-bootstrap-2"
Using theme: "theme-bootstrap-2"
Compiling for environment: ''
Javascripts: directory not found - skipping.
Stylesheets: (copying valid files)
  > bootstrap.min.css
  > google_prettify/default.css
  > google_prettify/desert.css
  > google_prettify/sons-of-obsidian.css
  > google_prettify/sunburst.css
  > google_prettify/twitter-bootstrap.css
  > style.css
Widgets: (copying valid files)
  > syntax/javascripts/prettify.js
/Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/collection_view.rb:15:in `sort': comparison of Ruhoh::Resources::Pages::ModelView with Ruhoh::Resources::Pages::ModelView failed (ArgumentError)
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/collection_view.rb:15:in `all'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/compiler.rb:7:in `run'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh.rb:156:in `block in compile'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh.rb:153:in `each'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh.rb:153:in `compile'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh/programs/compile.rb:15:in `compile'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh/client.rb:113:in `block in compile'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh/client.rb:112:in `compile'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/lib/ruhoh/client.rb:45:in `initialize'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/bin/ruhoh:41:in `new'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruhoh-2.6/bin/ruhoh:41:in `<top (required)>'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/bin/ruhoh:23:in `load'
    from /Users/pzol/.rbenv/versions/2.0.0-p353/bin/ruhoh:23:in `<main>'
```

**Comment by jwhitehorn** [comment]
I ran into this as well after adding a CNAME file with `jason.whitehorn.ws`.

**Comment by pzol** [comment]
This happens not only if you add CNAME...

**Comment by shime** [comment]
I was also struggling with this and found [this simple workaround](https://github.com/shime/shime.github.com/commit/1d49fde7a610598ec6cf0d306449a1358191fe74).
