### ISSUE TITLE
invalid byte sequence trying to run ruhoh server

### ISSUE THREAD

**Issue by masukomi** [ruhoh/ruhoh.rb#277]
Following the Quick Start.

```
bundle exec ruhoh server 9292
/Users/masukomi/workspace/ruhoh-site/vendor/bundle/gems/ruhoh-2.6/lib/ruhoh/parse.rb:37:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
from /Users/masukomi/workspace/ruhoh-site/vendor/bundle/gems/ruhoh-2.6/lib/ruhoh/parse.rb:37:in `page_file'
from /Users/masukomi/workspace/ruhoh-site/vendor/bundle/gems/ruhoh-2.6/lib/ruhoh/base/page_like.rb:59:in `parse_page_file'
```

**Comment by Stebalien** [comment]
One of your files (layouts, post, etc.) isn't utf-8 encoded.

**Comment by debo** [comment]
@masukomi the directory_watcher gem looks for every file and folders you have in your project. If like me for example you have bunlder configured to install gems locally for example or bin files you might want to make sure those files/folders are not parsed via **_config.yml**_ with something like:

``` yaml
'folder-that-might-causes-problem':
  'use': 'ignore'
```

Let me know if that's been the case

**Comment by ameuret** [comment]
If the advices above do not solve your case, make sure that you are not running into the bug highlighted by #281, fixed by 1c7df99. See a quick workaround in #293.
