### ISSUE TITLE
Compile yields problems with collated posts

### ISSUE THREAD

**Issue by ekstroem** [ruhoh/ruhoh.rb#301]
Hi everyone.

Fairly new to ruhoh and have run into a problem I cannot find a solution to. Whenever I run `bundle exec ruhoh publish rsync` I get the following error

```
/Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/collection_view.rb:44:in `block in collated': undefined method `strftime' for nil:NilClass (NoMethodError)
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/collection_view.rb:43:in `each'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/collection_view.rb:43:in `each_with_index'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/collection_view.rb:43:in `collated'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/context.rb:129:in `[]'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/context.rb:129:in `find'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/views/rmustache.rb:7:in `find'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:40:in `block in render'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:39:in `each'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:39:in `reduce'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:39:in `render'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:43:in `render'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache.rb:121:in `render'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/base/page_viewable.rb:49:in `content'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/context.rb:129:in `[]'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/context.rb:129:in `find'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/views/rmustache.rb:7:in `find'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:79:in `block in render'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:78:in `each'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:78:in `reduce'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:78:in `render'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache/template.rb:43:in `render'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/mustache-0.99.8/lib/mustache.rb:121:in `render'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/views/master_view.rb:33:in `render_full'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/compiler.rb:15:in `block (2 levels) in run'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/compiler.rb:15:in `open'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/compiler.rb:15:in `block in run'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/compiler.rb:11:in `each'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/resources/pages/compiler.rb:11:in `run'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh.rb:156:in `block in compile'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh.rb:153:in `each'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh.rb:153:in `compile'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/programs/compile.rb:15:in `compile'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/publish/rsync.rb:20:in `run'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/client.rb:138:in `publish'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/lib/ruhoh/client.rb:45:in `initialize'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/bin/ruhoh:41:in `new'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/gems/ruhoh-2.6/bin/ruhoh:41:in `<top (required)>'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/bin/ruhoh:23:in `load'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/bin/ruhoh:23:in `<main>'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/cld189/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

I've tracked the error down to the file `theme-bootstrap-2/_root/archive.html` which is fairly simple and looks like this

```
{{# posts.collated }}
  {{> posts_collate }}
{{/ posts.collated }}
```

It's the first and last line that gives me the problems. If I remove those then everything's dandy and the site compiles. However, I'd really like the collated posts. What am I doing wrong?

**Comment by ekstroem** [comment]
Okay.

I found a fix but have no idea about what went wrong. I had pushed my repository to Github, and re-cloned it back again and the new version worked. The old one still doesn't but haven't found out why.
