### ISSUE TITLE
can't make it work on windows

### ISSUE THREAD

**Issue by Jiraiyah** [ruhoh/ruhoh.rb#304]
I easily installed jekyll on windows and it is working, but when i run the final ruhoh server 9292 command i get these errors : 

C:\Users\Alireza_2\Desktop{Ruhoh}>ruhoh server 9292
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require': cannot load such file -- bundler/setup (LoadError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/bin/ruhoh:8:in '<top (required)>'
        from C:/Ruby22-x64/bin/ruhoh:23:in 'load'
        from C:/Ruby22-x64/bin/ruhoh:23:in '< main >'

C:\Users\Alireza_2\Desktop{Ruhoh}>

I first tried the bundle approach but the number of errors were much more than this, so i installed ruhoh gem manually, can anyone help?

**Comment by Jiraiyah** [comment]
this is the error i get when i try the bundle approach :

C:\Users\Alireza_2\Desktop{Ruhoh}\RUHOH>bundle exec ruhoh 9292
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.4-x64-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.4-x64-mingw32/lib/nokogiri.rb:29:in`rescue in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.4-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/summarizer.rb:1:in`require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/summarizer.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/base/page_viewable.rb:1:in`require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/base/page_viewable.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:6:in`require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:6:in `block (2 levels) in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:5:in`each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:5:in `block in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:127:in`chdir'
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:4:in`<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh.rb:25:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh.rb:25:in`<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in`block in require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in`require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/bin/ruhoh:9:in`<top (required)>'
        from C:/Ruby22-x64/bin/ruhoh:23:in `load'
        from C:/Ruby22-x64/bin/ruhoh:23:in`<main>'

C:\Users\Alireza_2\Desktop{Ruhoh}\RUHOH>bundle exec ruhoh help
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.4-x64-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.4-x64-mingw32/lib/nokogiri.rb:29:in`rescue in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.4-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/summarizer.rb:1:in`require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/summarizer.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/base/page_viewable.rb:1:in`require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/base/page_viewable.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:6:in`require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:6:in `block (2 levels) in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:5:in`each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:5:in `block in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:127:in`chdir'
        from C:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh/collections.rb:4:in`<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh.rb:25:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/lib/ruhoh.rb:25:in`<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in`block in require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in`require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruhoh-2.6/bin/ruhoh:9:in`<top (required)>'
        from C:/Ruby22-x64/bin/ruhoh:23:in `load'
        from C:/Ruby22-x64/bin/ruhoh:23:in`<main>'

C:\Users\Alireza_2\Desktop{Ruhoh}\RUHOH>
