### ISSUE TITLE
Error while publishing: class is properly namespaced Github

### ISSUE THREAD

**Issue by YTanev** [ruhoh/ruhoh.rb#305]
Hi,

I when I try to run 'bundle exec ruhoh publish github' command I get the following message

Using theme: "theme-bootstrap-2"
'Github' not found.
Ensure the service class is properly namespaced at Ruhoh::Publish::Github

Nothing else. 

What do I do to use this command? If any supplementary information is needed-I'll post it just specify
I use linux Mint 3.19.0-32-generic
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

Thank you

**Comment by plusjade** [comment]
@YTanev you have to install the `Github` publishing module. Please follow the instructions under "Github Pages" http://ruhoh.com/docs/2/publish/

Though I should just merge that in with the release already!

**Comment by YTanev** [comment]
@plusjade Thank you. Got that part through. But unfortunately it did not solve my problem completely.
Now after I run
`bundle exec ruhoh publish github`

from branch 'gh-pages', it gives me the following output:

```
Using theme: "theme-bootstrap-2"
Deploying to GitHub Pages.
(Settings based on origin remote name: https://github.com/YTanev/ytanev.github.io.git)
      Type: Project page.
    Source: 'master' branch.
  Compiled: 'gh-pages' branch.
Currently in deploy branch: 'gh-pages'; switching to source branch: 'master'...
Switched to branch 'master'
/home/mrk/prog/yavor/ytanev.github.io/plugins/github.rb:48:in `compile': undefined method `setup' for #<Ruhoh:0x00000002fd67e8> (NoMethodError)
    from /home/mrk/prog/yavor/ytanev.github.io/plugins/github.rb:32:in `run'
    from /var/lib/gems/1.9.1/gems/ruhoh-2.6/lib/ruhoh/client.rb:138:in `publish'
    from /var/lib/gems/1.9.1/gems/ruhoh-2.6/lib/ruhoh/client.rb:45:in `initialize'
    from /var/lib/gems/1.9.1/gems/ruhoh-2.6/bin/ruhoh:41:in `new'
    from /var/lib/gems/1.9.1/gems/ruhoh-2.6/bin/ruhoh:41:in `<top (required)>'
    from /usr/local/bin/ruhoh:23:in `load'
    from /usr/local/bin/ruhoh:23:in `<main>'

```

I have copied contents of github.rb as described in the manual but perhaps there is something that I'm missing now
