### ISSUE TITLE
ruhoh compile looks for underscore paths (Windows)

### ISSUE THREAD

**Issue by Painted-Fox** [ruhoh/ruhoh.rb#76]
I was able to install **ruhoh** on Windows after using the solution I attached to [issue #54](https://github.com/ruhoh/ruhoh.rb/issues/54#issuecomment-7583907).  I ran the following:

```
ruhoh new myblog
cd myblog
ruhoh compile
```

The ruhoh compile command complained with the following:

```
←[31mEmpty site_config.
Ensure ./_config.yml exists and contains valid YAML
←[0m
```

So, I created a copy of the `config.yml` file and renamed it to `_config.yml`.  Running the compile again got me this error:

```
0 Posts to process.
0 Pages to process.
C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:125:in `chdir': No such file or directory - C:/projects/myblog/_templates/themes/twitter/layouts (Errno::ENOENT)
        from C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:125:in `cd'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/lib/ruhoh/parsers/layouts.rb:24:in `files'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/lib/ruhoh/parsers/layouts.rb:9:in `generate'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/lib/ruhoh/db.rb:20:in `update'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/lib/ruhoh/db.rb:35:in `block in update_all'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/lib/ruhoh/db.rb:34:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/lib/ruhoh/db.rb:34:in `update_all'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/lib/ruhoh/client/client.rb:124:in `compile'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/lib/ruhoh/client/client.rb:22:in `initialize'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/bin/ruhoh:34:in `new'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruhoh-0.3.0/bin/ruhoh:34:in `<top (required)>'
        from C:/Ruby193/bin/ruhoh:19:in `load'
        from C:/Ruby193/bin/ruhoh:19:in `<main>'
```

So, it looks like **ruhoh** is looking for things in the wrong locations, at least on Windows.  I wonder if the underscore (_) is an artifact carried over from Jekyll.

**Comment by plusjade** [comment]
Yes the underscore is from earlier ruhoh versions which were based largely on jekyll. can you verify that you are running the latest ruhoh version?

```
$ ruhoh -v
```

**Comment by Painted-Fox** [comment]
Oh! My mistake.  I installed version 0.3.0 by mistake after having to reinstall it on windows.

Thank you!
