### ISSUE TITLE
1.0.rc bin/ruhoh runtime error

### ISSUE THREAD

**Issue by celadevra** [ruhoh/ruhoh.rb#79]
I cloned the 1.0.rc code tree, added a line to `ruhoh.gemspec`, build a new gem and installed it: 

``` zsh
(vim ruhoh.gemspec) lib/ruhoh/parsers/theme_config.rb
gem build ruhoh.gemspec
gem install ruhoh-1.0.0.alpha.gem
```

and established a new blog directory under ~/src:

``` zsh
ruhoh new testblog
cd testblog
```

`ruhoh compile` works, but 

``` zsh

➜  testblog git:(master) ruhoh draft test
/Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/client/client.rb:73:in `draft_or_post': undefined method `posts' for nil:NilClass (NoMethodError)
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/client/client.rb:61:in `draft'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/client/client.rb:22:in `initialize'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/bin/ruhoh:34:in `new'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/bin/ruhoh:34:in `<top (required)>'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/bin/ruhoh:19:in `load'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/bin/ruhoh:19:in `<main>'
➜  testblog git:(master) ruhoh posts
/Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh.rb:92:in `ensure_setup': Ruhoh has not been fully setup. Please call: Ruhoh.setup (RuntimeError)
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/parsers/posts.rb:11:in `generate'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/db.rb:29:in `update'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/client/client.rb:248:in `list'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/client/client.rb:227:in `posts'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/client/client.rb:22:in `initialize'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/bin/ruhoh:34:in `new'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/bin/ruhoh:34:in `<top (required)>'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/bin/ruhoh:19:in `load'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/bin/ruhoh:19:in `<main>'
➜  testblog git:(master) ruhoh payload
/Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/parsers/site.rb:9:in `generate': undefined method `site_data' for nil:NilClass (NoMethodError)
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/db.rb:25:in `update'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/db.rb:65:in `block in update_all'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/db.rb:64:in `each'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/db.rb:64:in `update_all'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/client/client.rb:238:in `payload'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/lib/ruhoh/client/client.rb:22:in `initialize'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/bin/ruhoh:34:in `new'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/gems/ruhoh-1.0.0.alpha/bin/ruhoh:34:in `<top (required)>'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/bin/ruhoh:19:in `load'
    from /Users/celadevra/.rvm/gems/ruby-1.9.3-p125/bin/ruhoh:19:in `<main>'
```

**Comment by plusjade** [comment]
@celadevra this should probably fix your problem: https://github.com/ruhoh/ruhoh.rb/pull/78#discussion_r1393605
I've added in the necessary commit, please fetch the latest on this branch and let me know if it solves the problem, thanks!

**Comment by celadevra** [comment]
The latest code worked all right, although I haven't tested all client functions extensively. Thank you, @plusjade and @MrWerewolf.

For the gem built from the code to work properly, the line `lib/ruhoh/parsers/theme_config.rb` is still needed in `ruhoh.gemspec`, though.
